### ISSUE TITLE
No funciona la integración de excel.

### ISSUE THREAD

**Issue by put0c0rd0b3** [put0cordob3/calcEstadistica#4]
```
Traceback (most recent call last):
  File "/Users/javier/git_calcEstadistica/calcEstadistica/calcEstadistica.py", line 13, in <module>
    columna = hoja.cell_value(1, c)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xlrd/sheet.py", line 420, in cell_value
    return self._cell_values[rowx][colx]
IndexError: list index out of range
```

**Comment by put0c0rd0b3** [comment]
#5 Trabajando en ello.
